#############################
# Preset 1 — COMPLETO
#############################
[preset 1]
fps
frame_timing=1
cpu_stats=1
gpu_stats=1
ram
vram
cpu_temp
gpu_temp
cpu_power
gpu_power
time

#############################
# Preset 2 — MÉDIO
#############################
[preset 2]
fps
cpu_stats=1
gpu_stats=1
ram
vram
time

#############################
# Preset 3 — LEVE (SÓ RELÓGIO)
#############################
[preset 3]
fps=0
cpu_stats=0
gpu_stats=0
ram=0
vram=0
frame_timing=0
time

#############################
# Preset 4 — SEM HUD
#############################
[preset 4]
no_display
