alias home "cd ~"
alias dwd "cd $HOME/Downloads"
alias ls "eza -lha --git"
alias disks "df -h"
alias ff "fastfetch"
alias bios "sudo systemctl reboot --firmware-setup"
alias cat "batcat"
alias mkdir "mkdir -pv"
alias install "sudo apt install -y"
alias uninstall "sudo apt remove -y"
alias update "sudo apt update && sudo apt upgrade -y"
alias cpu "lscpu"
alias memory "free -h"
alias mounts "mount | column -t"
alias psaux "ps aux"
alias psg "ps aux | grep -v grep | grep -i"
alias lsblk "lsblk -f"
alias ssd "df -h | grep sda"
alias man "tldr"
alias kernel "uname -r"
alias c "clear"
alias network_restart "sudo systemctl restart NetworkManager"
alias audio_restart "systemctl --user restart pipewire"
alias lg "lazygit"
alias rm_blank_spaces "rename 's/_/ /g' *"
