alias home "cd ~"
alias dwd "cd $HOME/Downloads"
alias ls "eza -lha --git"
alias disks "df -h"
alias ff "fastfetch"
alias bios "sudo systemctl reboot --firmware-setup"
alias cat "bat"
alias mkdir "mkdir -pv"

if command -v paru >/dev/null 2>&1
    alias install "paru -S --noconfirm"
    alias uninstall "paru -Rns"
    alias update "paru -Syu --noconfirm"
else if command -v yay >/dev/null 2>&1
    alias install "yay -S --noconfirm"
    alias uninstall "yay -Rns"
    alias update "yay -Syu --noconfirm"
else
    alias install "sudo pacman -S --noconfirm"
    alias uninstall "sudo pacman -Rns"
    alias update "sudo pacman -Syu --noconfirm"
end

alias cpu "lscpu"
alias memory "free -h"
alias mounts "mount | column -t"
alias psaux "ps aux"
alias psg "ps aux | grep -v grep | grep -i"
alias lsblk "lsblk -f"
alias ssd "df -h | grep sda"
alias man "tldr"
alias kernel "uname -r"
alias c "clear"
alias network_restart "sudo systemctl restart NetworkManager"
alias audio_restart "systemctl --user restart pipewire"
