font_family      CommitMono Nerd Font
font_size        10.0

background            #0e0e0e
foreground            #d0d0d0

cursor                #404040
cursor_text_color     #0e0e0e
cursor_shape          beam
cursor_beam_thickness 0.5

selection_background  #aaaaaa
selection_foreground  #0e0e0e

color0  #1a1a1a
color1  #777777
color2  #b0b0b0
color3  #c0c0c0
color4  #e0e0e0
color5  #999999
color6  #bbbbbb
color7  #d0d0d0

color8  #444444
color9  #888888
color10 #c8c8c8
color11 #d8d8d8
color12 #f0f0f0
color13 #aaaaaa
color14 #cccccc
color15 #f0f0f0
